name: GitHub Actions Workflow for Building, Pushing Docker Images, and Deploying

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image from root directory
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            romansth/melodyquest-frontend:latest
            romansth/melodyquest-frontend:${{ github.sha }}

      - name: Build and push Docker image from server directory
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            romansth/melodyquest-backend:latest
            romansth/melodyquest-backend:${{ github.sha }}

      - name: Post Docker Hub logout
        run: docker logout

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend to Render using deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}

      - name: Deploy backend to Render using deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}